### ISSUE TITLE
publish 1.3.0 version for scala 2.11.x

### ISSUE THREAD

**Issue by antonkulaga** [playframework/scalatestplus-play#17]
According to maven central the latest version is 1.3.0. But it is only published for Scala 2.10, please publish it for scala 2.11

**Comment by bvenners** [comment]
That's odd. I don't remember why we wouldn't have released that for 2.11, but we'll investigate.

**Comment by antonkulaga** [comment]
Just look at http://search.maven.org/#search%7Cga%7C1%7Cscalatestplus-play

Here you can see that version 1.2.0 is published for play 2.11 and version 1.3.0 is published for play 2.10 (but not for play 2.11)

**Comment by bvenners** [comment]
Yes, I already had looked actually. I was just saying I'm not sure why we would have left 2.11 out. In other words, yes we left it out, and erhaps we had a reason, but I can't remember what that reason might have been. Regardless we will try and release one Monday.

**Comment by cheeseng** [comment]
hi @antonkulaga the reason is that 1.3.x is built for play 2.2.x, scala 2.11 is only officially supported by play 2.3.x: 

https://www.playframework.com/changelog

so for play 2.3.x you should use scalatestplus-play 1.1.x/1.2.x series, you can refer to versioning reference here: 

http://scalatest.org/plus/play/versions

**Comment by marcospereira** [comment]
Closing since this is now outdated.
