### ISSUE TITLE
Question about Sonatype permissions / groupId

### ISSUE THREAD

**Issue by mkurz** [playframework/scalatestplus-play#374]
Right now this library is published under `org.scalatestplus.play`, but [we don't have permissions](https://github.com/playframework/scalatestplus-play/actions/runs/3203396941/jobs/5233442610) to publish to that groupId (yet).

So either we get permissions to do so or we change to `com.typesafe.play`.

@bvenners @cheeseng So you have different "plus" projects: https://www.scalatest.org/plus, all publishing under `org.scalatestplus`. I am ok to keep the current groupId `org.scalatestplus..play` to stay consistent with the other projects. I just commented on the related sonatype JIRA issue, could you please comment there (https://issues.sonatype.org/browse/OSSRH-20136) as well and approve the `playframework` user so it can publish artifacts under `org.scalatestplus..play`? Thanks!

**Comment by mkurz** [comment]
Also, can you explain a bit of the history of this scalatestplus-play project? Why is it actually hosted within the playframework GitHub organisation? Was that always the case or did it move there from somewhere else?
All other "plus" projects are hosted in the scalatest org:
* https://github.com/scalatest/scalatestplus-selenium
* https://github.com/scalatest/scalatestplus-junit
* https://github.com/scalatest/scalatestplus-scalacheck
* https://github.com/scalatest/scalatestplus-testng
* https://github.com/scalatest/scalatestplus-easymock
* https://github.com/scalatest/scalatestplus-jmock
* https://github.com/scalatest/scalatestplus-mockito

So I am wondering if we should move this project here to the scalatest org as well and you keep maintaining it?
I saw the Artima copyright in each source file:
https://github.com/playframework/scalatestplus-play/blob/9e4ccaa625fd633703fcc144c5cadb539ff952ab/module/src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala#L2
So does Artima officially maintain the project? I guess you have heard that Play is not longer maintained by Lightbend but the community, so if Artima keep maintaining scalatestplus-play, I think we should consider moving the repo.

What do you think?

**Comment by bvenners** [comment]
@mkurz Happy to give you permission to publish under org.scalatestplus.play. The history of the project is we started it, then at some point we passed the baton to the Play team at Typesafe/Lightbend. We joked that we could rename it to org.playplus.scalatest, because addition is commutative. But we didn't seriously consider a name change. We left it with the same name because everyone already was using that name in their source code.

Mainly the Play team had been maintaining it for many years. We (the ScalaTest team) had originally created it, and maintained it the first several years. I'm not sure what's going on with Play now that Lightbend has stopped supporting it. To what extent is the community volunteering to keep it going?

**Comment by mkurz** [comment]
Ping @bvenners - can you please comment on https://issues.sonatype.org/browse/OSSRH-20136? Thanks!

**Comment by bvenners** [comment]
@mkurz Sorry for the delay. Have been busy with family stuff. I added the comment on sonatype.

**Comment by mkurz** [comment]
Thanks Bill!
